markdown: kramdown
plugins:
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
    values:
      lang: "en"
  - scope:
      path: "best-google-apps"
    values:
      title: "The best apps to improve your Google Workspace (G Suite)"
      description: Choose from 100+ hand-curated collections of free & paid Gmail Apps to enhance your Google Workspace (formerly G Suite apps)
      og_title: "The best apps to improve your Google Workspace (G Suite)"
      og_description: Choose from 100+ hand-curated collections of free & paid apps to enhance your Google Workspace (formerly G Suite apps)
      list: "(X) best apps"
